spring:
  # 数据源配置
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/foodie-shop?useUnicode=true&characterEncoding=utf8mb4
    username: root
    password: root
    hikari:
      # 等待连接池分配连接的最长时长（毫秒）
      connection-timeout: 30000
      #最小连接数
      minimum-idle: 5
      # 最大连接数
      maximum-pool-size: 20
      # 自动提交
      auto-commit: true
      # 连接超时最大时长（毫秒）
      idle-timeout: 600000
      # 连接池名字
      pool-name: DataSourceHikariCP
      # 连接的声明时长
      max-lifetime: 1800000
      connection-test-query: SELECT 1


mybatis:
  type-aliases-package: com.imooc.pojo
  mapper-locations: classpath:mapper/*.xml